### ISSUE TITLE
Details: Safari renders additional icon

### ISSUE THREAD

**Issue by McManning** [osuresearch/ui#1]
See screenshot:

![Screen Shot 2023-01-10 at 9 15 01 AM](https://user-images.githubusercontent.com/1057607/211575521-2b1fe5da-0511-47ce-865a-82b00b4cfd9a.png)

**Comment by helloLilyX** [comment]
https://github.com/tailwindlabs/tailwindcss/issues/924 talks about this problem. I need to figure out how to add `details > summary::-webkit-details-marker {
  display: none;
}` to tailwind

**Comment by McManning** [comment]
It looks like that'd be a good candidate to add to our base styles here: https://github.com/osuresearch/ui/blob/alpha/src/theme/index.css
