### ISSUE TITLE
Add progress component

### ISSUE THREAD

**Issue by McManning** [osuresearch/ui#13]
Key features to touch on:

- Announce intervals via an aria-live region at some fixed rate, e.g. every 5 seconds or at certain key percentages (10%, 50%, etc) 
- Support unbounded/indeterminate and determinate progress bar variants
- Possibly a content ref so we can flag it as busy 

React Aria [already has a progress bar hook](https://react-spectrum.adobe.com/react-aria/useProgressBar.html) so drive it off of that.

I like Fluent UI's lightweight progress bar. Maybe something like that:

https://developer.microsoft.com/en-us/fluentui#/controls/web/progressindicator

**Comment by McManning** [comment]
For indeterminate animation:

This is a pretty simple example: https://csslayout.io/indeterminate-progress-bar/ 
We can add a new animation into the tailwind.config.js for indeterminate progress bars to support it since it doesn't seem like one is built in. Let's call it "animate-scroll" to be consistent with how tailwind names other animations. 

For the visuals itself:

- Should span the full width of it's container (so the root component should probably be a `<Box w="full" ...>`) 
- Either 2px or 4px tall progress bars, whichever looks nicer. This'll be consistent with our border widths elsewhere in the framework.
- Small font size for the text and percentage completion

We won't worry about the other notes about aria-live regions and content refs yet. I think we should split up this issue into a simple progress bar and a more complicated / wrapping component that ties progress bar + content together for a11y.

**Comment by helloLilyX** [comment]
#41 solves some parts of this issue
