### ISSUE TITLE
LookupField - Submit item key not value

### ISSUE THREAD

**Issue by McManning** [osuresearch/ui#20]
LookupField is submitting the value in the input field. This needs to instead associate the `Item.key` to the field on submit.

Use cases:
- Feature parity with our v4 Lookup
- Human-readable display values (person name) versus submitted data (employee ID)

For situations where someone wants the text value to equate the submitted value, they should use a ComboBoxField.

**Comment by McManning** [comment]
Some more details for this issue:

When a `LookupField` is submitted alongside a form, I'd like the key e.g. `dx12` to be submitted in place of the lookup's display value. The display value is being submitted instead because the underlying `input` is given the `name` attribute to submit. 

A lot of this is handled by React-Aria so I'm not sure what level of control we have in changing it to be a hidden input that submits the key under the correct field name. 

Good place to test this in Storybook: https://osuresearch.github.io/ui/docs/?path=/story/examples-forms--uncontrolled 

I'd expect the FormData to report back `"lookupField": "dx11"` and not `"lookupField": "DirectX 11"`

**Comment by helloLilyX** [comment]
Note for myself: need to fix the problem in `ComboBoxField` since `LookupField` uses `useComboBox` and `useComboBoxState` hooks

**Comment by helloLilyX** [comment]
Also a note for myself: restore package-lock.json before committing my changes
