### ISSUE TITLE
Button - Text color needs to be black for the primary variant 

### ISSUE THREAD

**Issue by helloLilyX** [osuresearch/ui#42]
[https://osuresearch.github.io/ui/docs/?path=/story/components-button--primary&args=isDisabled:true](url)

**Comment by andybeas** [comment]
I want to contribute on this. Please allow me to do so.

**Comment by McManning** [comment]
> I want to contribute on this. Please allow me to do so.

Hi andybeas,

Thanks for wanting to contribute!

Right now we are only accepting contributions from our development team here at Ohio State. But we are in the process of working out a plan to support outside contributions in the near future.

**Comment by andybeas** [comment]
Hey there, 
I understand the situation. Please do let me know whenever you guys are planning to collaborate with people outside the state. I would love to contribute.
