### ISSUE TITLE
<Chip> component shouldn't support `null` as an input value

### ISSUE THREAD

**Issue by helloLilyX** [osuresearch/ui#81]
`<Chip>{null}</Chip>` shows up as a thin line

**Comment by McManning** [comment]
This is just typical React component behaviour. `null` is valid but will render no content. You should ensure that you have content to actually inject into a chip and fallback to a placeholder if you don't, or don't render the chip at all - depending on your particular use case. 

E.g.

```tsx
{value && <Chip>{value}</Chip>}

OR

<Chip>{value ?? 'fallback'}</Chip>
```
