### ISSUE TITLE
DataTable: The same visible arrows, when in a non-sorted state and using the gray `#cccccc`, do not meet the 3:1 color contrast ration requirement for non-text components.   

### ISSUE THREAD

**Issue by McManning** [osuresearch/ui#92]
•	[WCAG 1.4.11 Non-Text Contrast](https://www.w3.org/WAI/WCAG21/Understanding/non-text-contrast)
•	Recommendation: Darken the gray until 3:1 is reached.

For context (from PI Portal wcag eval):
![image](https://github.com/osuresearch/ui/assets/1057607/6ad84759-ce81-4928-a3c3-24b88aed2cb0)

**Comment by helloLilyX** [comment]
CSS hacking on the PrimeReact DataTable?

**Comment by McManning** [comment]
@helloLilyX yea, so we have style overrides for their DataTables here: https://github.com/osuresearch/ui/blob/main/src/sass/overrides/_datatables.scss

You can just add a rule there to target those icons and update the color. Looks like their CSS selector is `p-sortable-column-icon`:

![image](https://github.com/osuresearch/ui/assets/1057607/c81fd8be-d646-41f5-9f15-04eb303ed81a)
